#import "@preview/acrostiche:0.3.1": *

== Visualization

MOSAIK is able to generate visualizations of the microservice decomposition process.
The information extraction step can be visualized as a dependency graph where the vertices represent the classes of the monolithic application, and the edges represent the dependencies between the classes.
The edges are weighted according to the calculated coupling factor between the classes.
Depending on the weights assigned to the structural, logical, and contributor coupling, the generated graph can visualize a different view of the monolithic application.

#grid(
  columns: (40%, 60%),
  gutter: 1em,
  [
    #figure(
      image("/figures/directed.svg"),
      caption: [Example visualization output],
    )
  ],
  [
    Visualization of the decomposition process yields a dependency graph where the vertices represent the microservice candidates, and the edges represent the dependencies between the microservice candidates.
    The graphs generated by the different steps in the decomposition process are saved as CSV files.
    The visualizations are generated using a custom implementation, that converts the graphs into the DOT language#footnote[#link("https://graphviz.org/doc/info/lang.html")[https://graphviz.org/doc/info/lang.html]], before rendering them as images using the `dot` tool from the Graphviz package#footnote[#link("https://graphviz.org/")[https://graphviz.org/]].

  ]
)
